### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by Simon-Will** [Simon-Will/nlmaps-tools#1]
Think about what to do with the mrl <-> lin conversion code from Carolin. Either rewrite it (would be a good idea anyway) or ask for her permission of licensing it.

**Comment by isspek** [comment]
Hi @Simon-Will
Thanks for your work. I would like to ask the license of the work. Because I plan to use as a part of a prototype and might enhance.
Thank you!

**Comment by Simon-Will** [comment]
Hi @isspek, thanks for your interest! If you'd like to share, I'd very much like to know what you're planning to work on. I still maintain https://nlmaps.org/ and I'd like to improve it, too. So maybe there's some common goal somewhere.

Regardless of that, I'd like to choose a permissive license for this, such as the MIT license. @carolinlawrence, I cannot decide on a license for this project on my own because [the mrl module](https://github.com/Simon-Will/nlmaps-tools/tree/master/nlmaps_tools/mrl) is your work for the most part. When I asked you about it two or three years ago, you told me that I can use it and make it accessible provided I make it clear that it's yours. Would you agree to license the whole project under the MIT license?

**Comment by carolinlawrence** [comment]
Hi @Simon-Will, happy to hear that there is still use for the mrl module, please feel free to use the MIT license for that prat of the project as well.

**Comment by isspek** [comment]
@Simon-Will could you send me an email to my Gmail address: ibarsch.arbeit? I would be happy for discussing it.

**Comment by Simon-Will** [comment]
That's great, @carolinlawrence. I added the MIT license to the project.

@isspek, I'm going to send you a message.
